name: FFmpeg Installation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install the ffmpeg
        run: |
          curl -s https://raw.githubusercontent.com/XniceCraft/ffmpeg-colab/master/install
          chmod +x ./install
          ./install

      - name: Test
        run: |
          wget http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4
          ffmpeg -i ForBiggerBlazes.mp4 -c:a libfdk_aac -b:a 192k -c:v libopenh264 -b:v 1000k hi.mp4
